int desayunoBitacora = 0;
int comidaBitacora = 0;
int cenaBitacora = 0;
int estadoAnimoBitacora;
double temperaturaBitacora = 0.0;
int presionSistolicaBitacora = 0;
int presionDiastolicaBitacora = 0;
int glucosaBitacora = 0;
int oxigenoBitacora = 0;
int idServicioBitacora = 0;
int idColaboradorBitacora = 0;
List<int> actividadesBitacora = [];